/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NimCheckout {
    /**
    * The name of your app, should be as short as possible.
    */
    'app': string;
    /**
    * Extra data that should be sent with the transaction.
    */
    'data': string;
    /**
    * Transaction fee in luna. Default: 0
    */
    'fee': number;
    /**
    * An image URL. Must be on the same origin as the request is sent from. Should be square and at least 146x146 px.
    */
    'logoUrl': string;
    /**
    * The network you want to use. Can be 'main' or 'test'.
    */
    'network': 'main' | 'test';
    /**
    * The human-readable address of the recipient (your shop/app).
    */
    'recipient': string;
    /**
    * The theme of the button. Use light when using against dark background.
    */
    'theme': 'dark' | 'light';
    /**
    * Value of the transaction, in Luna. 1 NIM = 100000 Luna.
    */
    'value': number;
  }
}

declare global {


  interface HTMLNimCheckoutElement extends Components.NimCheckout, HTMLStencilElement {}
  const HTMLNimCheckoutElement: {
    prototype: HTMLNimCheckoutElement;
    new (): HTMLNimCheckoutElement;
  };
  interface HTMLElementTagNameMap {
    'nim-checkout': HTMLNimCheckoutElement;
  }
}

declare namespace LocalJSX {
  interface NimCheckout {
    /**
    * The name of your app, should be as short as possible.
    */
    'app'?: string;
    /**
    * Extra data that should be sent with the transaction.
    */
    'data'?: string;
    /**
    * Transaction fee in luna. Default: 0
    */
    'fee'?: number;
    /**
    * An image URL. Must be on the same origin as the request is sent from. Should be square and at least 146x146 px.
    */
    'logoUrl'?: string;
    /**
    * The network you want to use. Can be 'main' or 'test'.
    */
    'network'?: 'main' | 'test';
    /**
    * Emitted when an error happened during checkout or it is canceled
    */
    'onNimCheckoutError'?: (event: CustomEvent<any>) => void;
    /**
    * Emitted when checkout is successful
    */
    'onNimCheckoutSuccess'?: (event: CustomEvent<any>) => void;
    /**
    * The human-readable address of the recipient (your shop/app).
    */
    'recipient'?: string;
    /**
    * The theme of the button. Use light when using against dark background.
    */
    'theme'?: 'dark' | 'light';
    /**
    * Value of the transaction, in Luna. 1 NIM = 100000 Luna.
    */
    'value'?: number;
  }

  interface IntrinsicElements {
    'nim-checkout': NimCheckout;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'nim-checkout': LocalJSX.NimCheckout & JSXBase.HTMLAttributes<HTMLNimCheckoutElement>;
    }
  }
}


